version: 2

jobs:
  build:
    docker:
      - image: "debian:buster"
    steps:
      - checkout
      - run:
          name: Install dependencies GCC
          command: 'apt-get update && apt-get install -y gcc make python3 python3-pip'
      - run:
          name: Install dependencies Python
          command: 'pip3 install -U pip && pip3 install -U setuptools && pip3 install -U norminette'
      - run:
          name: Build Philo
          command: 'cd philo && make'
      - run:
          name: Unit-Test Philo
          command: 'cd philo && make test_run'
      - run:
          name: Integration-Test Philo
          command: 'cd philo && make test_integration'
      - run:
          name: Build Philo Bonus
          command: 'cd philo_bonus && make'
      - run:
          name: Integration-Test Philo Bonus
          command: 'cd philo_bonus && make test_integration'